-- MySQL Script generated by MySQL Workbench
-- Sun Oct  9 17:19:09 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dream
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dream
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dream` DEFAULT CHARACTER SET utf8 ;
USE `dream` ;

-- -----------------------------------------------------
-- Table `dream`.`dreamer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dream`.`dreamer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NULL,
  `password` VARCHAR(64) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL,
  `last_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `stats` TINYINT(1) NOT NULL DEFAULT 1,
  `nick_name` VARCHAR(255) NOT NULL DEFAULT 'New Dreamer',
  `avatar_url` VARCHAR(255) NULL,
  `gender` VARCHAR(45) NULL,
  `job` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dream`.`wx_dreamer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dream`.`wx_dreamer` (
  `dreamer_id` INT NOT NULL,
  `openid` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`dreamer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dream`.`dream_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dream`.`dream_message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL DEFAULT 'PUBLIC' COMMENT 'PUBLIC,\nPRIVATE',
  `dreamer_id` INT NOT NULL,
  `content` VARCHAR(1000) NOT NULL,
  `image_url` VARCHAR(1000) NULL,
  `create_time` TIMESTAMP NULL,
  `last_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `stats` TINYINT(1) NOT NULL DEFAULT 1,
  `dream_type` VARCHAR(45) NOT NULL,
  `dream_type_content` VARCHAR(45) NULL,
  `dream_location_content` VARCHAR(45) NULL,
  `dream_location` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_dreamer_id` (`dreamer_id` ASC),
  INDEX `idx_type` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dream`.`dream_reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dream`.`dream_reply` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message_id` INT NOT NULL,
  `dreamer_id` INT NOT NULL,
  `reply_dreamer_id` INT NULL,
  `content` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL,
  `last_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `stats` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `idx_dreamer_id` (`dreamer_id` ASC),
  INDEX `idx_message_id` (`message_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dream`.`dream_greater`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dream`.`dream_greater` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message_id` INT NOT NULL,
  `dreamer_id` INT NOT NULL,
  `create_time` TIMESTAMP NULL,
  `last_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `stats` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `idx_dreamer_id` (`dreamer_id` ASC),
  INDEX `idx_message_id` (`message_id` ASC),
  UNIQUE INDEX `uni_dreamer_id_message_id` (`message_id` ASC, `dreamer_id` ASC))
ENGINE = InnoDB;

USE `dream` ;

-- -----------------------------------------------------
-- Placeholder table for view `dream`.`dream_message_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dream`.`dream_message_view` (`message_id` INT, `dreamer_id` INT, `content` INT, `type` INT, `image_url` INT, `message_create_time` INT, `message_stats` INT, `nick_name` INT, `avatar_url` INT, `gender` INT, `dreamer_create_time` INT, `dreamer_stats` INT);

-- -----------------------------------------------------
-- Placeholder table for view `dream`.`dream_reply_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dream`.`dream_reply_view` (`reply_id` INT, `message_id` INT, `dreamer_id` INT, `content` INT, `reply_dreamer_id` INT, `reply_create_time` INT, `reply_stats` INT, `nick_name` INT, `avatar_url` INT, `dreamer_stats` INT);

-- -----------------------------------------------------
-- Placeholder table for view `dream`.`dream_greater_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dream`.`dream_greater_view` (`greater_id` INT, `message_id` INT, `dreamer_id` INT, `greater_create_time` INT, `greater_stats` INT, `nick_name` INT, `avatar_url` INT, `dreamer_stats` INT);

-- -----------------------------------------------------
-- View `dream`.`dream_message_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dream`.`dream_message_view`;
USE `dream`;
CREATE  OR REPLACE VIEW `dream_message_view` AS 
select dm.`id` message_id,dm.`dreamer_id`,dm.`content`,dm.`type`,dm.`image_url`
,dm.`create_time` message_create_time,dm.stats message_stats
,d.nick_name,d.avatar_url,d.gender,d.create_time dreamer_create_time,d.stats dreamer_stats
from dream_message dm left join dreamer d on dm.dreamer_id = d.id;

-- -----------------------------------------------------
-- View `dream`.`dream_reply_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dream`.`dream_reply_view`;
USE `dream`;
CREATE  OR REPLACE VIEW `dream_reply_view` AS
select dr.`id` reply_id,dr.message_id,dr.`dreamer_id`,dr.`content`,dr.`reply_dreamer_id`
,dr.`create_time` reply_create_time,dr.stats reply_stats
,d.nick_name,d.avatar_url,d.stats dreamer_stats
from dream_reply dr left join dreamer d on dr.dreamer_id = d.id;

-- -----------------------------------------------------
-- View `dream`.`dream_greater_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dream`.`dream_greater_view`;
USE `dream`;
CREATE  OR REPLACE VIEW `dream_greater_view` AS
select dg.`id` greater_id,dg.message_id,dg.`dreamer_id`
,dg.`create_time` greater_create_time,dg.stats greater_stats
,d.nick_name,d.avatar_url,d.stats dreamer_stats
from dream_greater dg left join dreamer d on dg.dreamer_id = d.id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
