-- MySQL Script generated by MySQL Workbench
-- Mon Oct  3 16:40:47 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dream
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dream
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dream` DEFAULT CHARACTER SET utf8 ;
USE `dream` ;

-- -----------------------------------------------------
-- Table `dream`.`dreamer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dream`.`dreamer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NOT NULL,
  `last_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `stats` TINYINT(1) NOT NULL DEFAULT 1,
  `nickName` VARCHAR(255) NOT NULL,
  `avatar_url` VARCHAR(255) NULL,
  `gender` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nickName_UNIQUE` (`nickName` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dream`.`wx_dreamer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dream`.`wx_dreamer` (
  `dreamer_id` INT NOT NULL,
  `openid` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`dreamer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dream`.`dream_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dream`.`dream_message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL DEFAULT 'PUBLIC' COMMENT 'PUBLIC,\nPRIVATE',
  `dreamer_id` VARCHAR(45) NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `image_url` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NOT NULL,
  `last_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `stats` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dream`.`dream_reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dream`.`dream_reply` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message_id` INT NOT NULL,
  `dreamer_id` INT NOT NULL,
  `reply_dreamer_id` INT NULL,
  `content` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NOT NULL,
  `last_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `stats` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dream`.`dream_greater`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dream`.`dream_greater` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message_id` INT NOT NULL,
  `dreamer_id` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL,
  `last_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `stats` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
